### ISSUE TITLE
Issues with creating Controllers with angel_container_generator

### ISSUE THREAD

**Issue by radzish** [angel-dart/angel#122]
Hello,

Where I can get example, on what should be done to add Controller, how properly annotate it, and how generate reflector stuff so all of this can be compiled with dart2native tool.

**Comment by thosakwe** [comment]
Check out the docs page: https://docs.angel-dart.dev/guides/controllers

**Comment by thosakwe** [comment]
Secondly, the title of this issue says you’re having trouble with angel_container_generator. Are you running into a bug, etc.?

**Comment by radzish** [comment]
1. I would like to know what should I do to make generator to be aware of Controller I am creating, should I annotate Controller with @contained, or it is not required?

2. When I am annotating with  @contained it is kind of generate something like "prod.reflectable.dart", but I am getting errors in the process of generating like:
```
[SEVERE] reflectable:reflectable on bin/prod.dart:
`reflectedTypeArguments` where an actual type argument (possibly nested) is void
[SEVERE] reflectable:reflectable on bin/dev.dart:
`reflectedTypeArguments` where one actual type argument is FutureOr<dynamic> Function(RequestContext<dynamic>, ResponseContext<dynamic>)
[
```

3. I am not sure where is the best place to put initializeReflectable(). I can not put it in main, because then isolate that runs server will not know about this initialization. Should I put it in lib/src/routes/controllers/ ? But then how can I reference it from bin/prod.reflectable.dart ?

More to come, but first I need to resolve those 3 things ;)

**Comment by thosakwe** [comment]
`angel_container_generator` is more or less just a wrapper around `reflectable` (Sorry, seems like I forgot to write good docs on this).

`package:reflectable` is preferable, because it's a Dart team package, but it has known limitations: https://pub.dev/packages/reflectable#known-limitations

Among these limitations is inability to reflect functions and closures, so it's really best-effort. 

You should annotate with `@contained` anything you want to appear in the generated reflection code. You'll likely also want a `@GlobalQuantifyCapability`, as seen here: https://github.com/angel-dart/container/blob/master/angel_container_generator/test/reflector_test.dart

As for `initializeReflectable`, call it as early as possible, at least before controllers are mounted. It's up to you exactly where to place it, but a pretty foolproof place to put it is right at the start of your application's main `configureServer` function (assuming you generated the project with `angel init`).

---

Overall, though, controllers and other reflection (the `ioc` function) make most sense on the Dart VM, where reflection is available, and no extra codegen step is needed.
 
Controllers are just a nice wrapper over the core routing functionality, so if `dart2native` is a top priority for you, I would just avoid using reflection in the first place.

**Comment by radzish** [comment]
Thanks for the answer. And thanks in general for rather good framework. My motivation to use dart2native is just because I am planning to run in serverless environment (Google Cloud Run). According to my tests it performs much better than in JIT mode.

I still could not generate stuff properly with reflectable, so at this point I will move towards simple manually written controllers. 

However it would be nice to see step-by-step guide describing how one can create working app running with reflectable generated stuff over Controllers, DI and with no mirrors.

**Comment by thosakwe** [comment]
Truthfully, I can't say that writing more guides is the #1 priority right now. I'm working on updates to the ORM, GraphQL, and the core framework itself first.

As it is right now, you can already use Angel in AOT without major changes, as long as you avoid Controllers/ioc/MirrorsReflector (the `Container` class works without any reflection; however, constructor parameter injection is where mirrors are needed).

I'll add an issue to get a guide written eventually, but if you find a way to do it and think it would make sense to add it to the docs site directly, docs page can be added in Markdown here: https://github.com/angel-dart/gitbook

Thanks for the feedback. I'm going to keep this issue until I get around to improving the docs.
