### ISSUE TITLE
Angel Reliability

### ISSUE THREAD

**Issue by j209** [angel-dart/angel#129]
I’m impressed with your work and the Angel framework. I can see it having the potential to become the most popularly used Dart server backend. The only thing that is making me hesitate is the stability question: Will you still be maintaining it in five years? If you can figure out a way to turn it into a profitable startup or to get the community involved in the development process, that would go a long way in reassuring people that investing the time to learn the framework is worth it. Also, dropping the emoji scattered across the official site would make it look more professional .
[HTTP server frameworks for Dart](https://medium.com/@suragch/web-server-frameworks-for-dart-197a073299eb)

**Comment by thosakwe** [comment]
Hi, thanks for the feedback. Appreciate it. I've been trying since 2016 to get people involved, with moderate success. Fortunately, there is a decent amount of people who send pull requests to Angel repositories, and their changes are then merged in. One of my goals soon is to come up with a roadmap for further development (at this point, the goal is just maintenance, there aren't really new features to add).

I disagree about the emoji - did you see my response to the linked article? I addressed that directly. I think that it's such a trivial/unimportant thing, that if people are even bothered by that, it's good that they're interested. Also, in the JavaScript community, packages are littered with emoji, and that has absolutely zero effect on whether people use them (as you can see by the massive amount of people in that community). Last, but not least, the emoji aren't there for no reason - they serve the same purpose as other icons, and are simply to add visual flair... And there are *only five on the entire site*. I don't think it's all that deep.

Lastly, I recommend joining the Gitter chat for topics like this. Ideally, the issue tracker will be used only for bug reports: https://gitter.im/angel_dart/discussion
