### ISSUE TITLE
First app - connection error

### ISSUE THREAD

**Issue by avstudios** [angel-dart/angel#25]
Hi, 
Firstly I would like to thank you for your hard work. I'm very pleased someone finally started creating full-stack framework for dart. Because it's a beta version I thought it's a good time have a look at it.

Base on the installation guide I run ```angel start``` and all work fine. Then I open ```http://localhost:3000``` the app in the browser and then I'm getting the bellow error in the console:

```INFO: 2017-02-06 15:21:25.795569: 200 GET / (11 ms)
SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 57584
#0      ProxyLayer.serveFile.<serveFile_async_body> (package:angel_proxy/src/proxy_layer.dart)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _rootRunBinary (dart:async/zone.dart:1170)
#3      _CustomZone.runBinary (dart:async/zone.dart:1049)
#4      _FutureListener.handleError (dart:async/future_impl.dart:146)
#5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#7      _Future._completeError (dart:async/future_impl.dart:485)
#8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
#9      _rootRun (dart:async/zone.dart:1150)
#10     _CustomZone.run (dart:async/zone.dart:1026)
#11     _CustomZone.runGuarded (dart:async/zone.dart:924)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

SEVERE: 2017-02-06 15:21:26.330914: /images/favicon.png: Unhandled exception occurred - 
SEVERE: 2017-02-06 15:21:26.331358: 
#0      ProxyLayer.serveFile.<serveFile_async_body> (package:angel_proxy/src/proxy_layer.dart)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _rootRunBinary (dart:async/zone.dart:1170)
#3      _CustomZone.runBinary (dart:async/zone.dart:1049)
#4      _FutureListener.handleError (dart:async/future_impl.dart:146)
#5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)```
#6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#7      _Future._completeError (dart:async/future_impl.dart:485)
#8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
#9      _rootRun (dart:async/zone.dart:1150)
#10     _CustomZone.run (dart:async/zone.dart:1026)
#11     _CustomZone.runGuarded (dart:async/zone.dart:924)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)```

**Comment by thosakwe** [comment]
By default there is a reverse proxy set up to run over pub serve. If you
run pub serve (or remove the PubServeLayer usage in
lib/src/routes/routes.dart), the error will go away.

Cheers!

On Feb 6, 2017 11:12 AM, "Marcin Sydor" <notifications@github.com> wrote:

Hi,
Firstly I would like to thank you for your hard work. I'm very pleased
someone finally started creating full-stack framework for dart. Because
it's a beta version I thought it's a good time have a look at it.

Base on the installation guide I run angel start and all work fine. Then I
open http://localhost:3000 the app in the browser and then I'm getting the
bellow error in the console:

SocketException: OS Error: Connection refused, errno = 61, address =
localhost, port = 57584
#0      ProxyLayer.serveFile.<serveFile_async_body>
(package:angel_proxy/src/proxy_layer.dart)
#1      _asyncErrorWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:34)
#2      _rootRunBinary (dart:async/zone.dart:1170)
#3      _CustomZone.runBinary (dart:async/zone.dart:1049)
#4      _FutureListener.handleError (dart:async/future_impl.dart:146)
#5      _Future._propagateToListeners.handleError
(dart:async/future_impl.dart:649)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#7      _Future._completeError (dart:async/future_impl.dart:485)
#8      _Future._asyncCompleteError.<anonymous closure>
(dart:async/future_impl.dart:537)
#9      _rootRun (dart:async/zone.dart:1150)
#10     _CustomZone.run (dart:async/zone.dart:1026)
#11     _CustomZone.runGuarded (dart:async/zone.dart:924)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:149)

SEVERE: 2017-02-06 15:21:26.330914: /images/favicon.png: Unhandled
exception occurred -
SEVERE: 2017-02-06 15:21:26.331358:
#0      ProxyLayer.serveFile.<serveFile_async_body>
(package:angel_proxy/src/proxy_layer.dart)
#1      _asyncErrorWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:34)
#2      _rootRunBinary (dart:async/zone.dart:1170)
#3      _CustomZone.runBinary (dart:async/zone.dart:1049)
#4      _FutureListener.handleError (dart:async/future_impl.dart:146)
#5      _Future._propagateToListeners.handleError
(dart:async/future_impl.dart:649)```
#6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#7      _Future._completeError (dart:async/future_impl.dart:485)
#8      _Future._asyncCompleteError.<anonymous closure>
(dart:async/future_impl.dart:537)
#9      _rootRun (dart:async/zone.dart:1150)
#10     _CustomZone.run (dart:async/zone.dart:1026)
#11     _CustomZone.runGuarded (dart:async/zone.dart:924)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:149)```

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/angel-dart/angel/issues/25>, or mute the thread

**Comment by avstudios** [comment]
Removing PubServeLayer line helped. Thanks.
