### ISSUE TITLE
angel start OSX 10.11.6 fails two separate ways

### ISSUE THREAD

**Issue by torchhound** [angel-dart/angel#30]
First ran `angel init demonic_chat` then `angel start` and got this error:
```
Starting server...
Unhandled error occurred: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 58886
#0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart:24:5)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _rootRunBinary (dart:async/zone.dart:1170)
#3      _CustomZone.runBinary (dart:async/zone.dart:1049)
#4      _FutureListener.handleError (dart:async/future_impl.dart:146)
#5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#7      _Future._completeError (dart:async/future_impl.dart:485)
#8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
#9      _rootRun (dart:async/zone.dart:1150)
#10     _CustomZone.run (dart:async/zone.dart:1026)
#11     _CustomZone.runGuarded (dart:async/zone.dart:924)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```
then tried `dart bin/server.dart` and got the same error. After this I tried to replicate this by running `angel init angel_test` and then `angel start` and got this error(`dart bin/server.dart` also throws this error):
```
Starting server...
Unhandled exception:
Could not import "package:intl/intl.dart" from "file:///Users/torchhound/angel_test/bin/common.dart": Could not resolve a package location for base at file:///Users/torchhound/angel_test/bin/server.dart
null
```

**Comment by thosakwe** [comment]
1. The application boilerplate is set up to connect to a MongoDB server. If none is running (i.e. a daemon), it will crash. There are three options: remove the database code from the application (not recommended, as this would require you to rewrite your application to use in-memory data stores for services, instead of a persistent DB), rewrite the code to support a different database you have running (RethinkDB is supported. PostgreSQL and a few others are on their way), or install MongoDB (simplest way). I will include documentation about this in the project README. The only issue people ever have with Angel is failures with angel init, and that is because I failed to provide a list of prerequisites to install. 

2. angel_test is an actual Pub package already, and it is imported by the 'angel_common' package, so creating your own package with the same name will inevitably crash your application. 

Hope I was of help!

**Comment by thosakwe** [comment]
Update: See [Prerequisites](https://github.com/angel-dart/angel/wiki/Installation-&-Setup#prequisites).

**Comment by torchhound** [comment]
I feel rather silly, thanks for the prompt help. Perhaps you could add installing MongoDB/having it running to the website in the Getting Started section. Great website by the way!

**Comment by thosakwe** [comment]
Great idea, and thank you very much!
